version: "3.9"

services:
  backend:
    build: .
    container_name: food-forum-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    depends_on: []
    environment:
      - DATABASE_URL=${DATABASE_URL}
