"""add unit to material and update post_material

Revision ID: 026b329a3d2a
Revises: bc562631a595
Create Date: 2025-06-10 17:43:48.022100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026b329a3d2a'
down_revision: Union[str, None] = 'bc562631a595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('unit', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'material', 'unit', ['unit'], ['name'])
    op.drop_constraint(op.f('post_material_unit_fkey'), 'post_material', type_='foreignkey')
    op.drop_column('post_material', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_material', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('post_material_unit_fkey'), 'post_material', 'unit', ['unit'], ['name'])
    op.drop_constraint(None, 'material', type_='foreignkey')
    op.drop_column('material', 'unit')
    # ### end Alembic commands ###
