"""add_steps_table_new

Revision ID: 036299d8bc7f
Revises: e120ba49472f
Create Date: 2025-06-11 21:11:21.874644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036299d8bc7f'
down_revision: Union[str, None] = 'e120ba49472f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step',
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step')
    # ### end Alembic commands ###
