"""create group_members table

Revision ID: 07eff5c13dfb
Revises: a9ed71b930b0
Create Date: 2025-06-11 14:03:55.562957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07eff5c13dfb'
down_revision: Union[str, None] = 'a9ed71b930b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_email_key', 'account', type_='unique')
    op.drop_constraint('account_username_key', 'account', type_='unique')
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=True)
    op.create_index(op.f('ix_account_username'), 'account', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_username'), table_name='account')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.create_unique_constraint('account_username_key', 'account', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('account_email_key', 'account', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
