"""add_favourites_and_favourite_posts

Revision ID: 221e3fe9f6c5
Revises: c95102e9f805
Create Date: 2025-06-12 21:28:54.242712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision: str = '221e3fe9f6c5'
down_revision: Union[str, None] = 'c95102e9f805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing tables if they exist
    op.execute('DROP TABLE IF EXISTS favourite_posts CASCADE')
    op.execute('DROP TABLE IF EXISTS favourites CASCADE')

    op.create_table('favourites',
        sa.Column('favourite_id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('account_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('favourite_name', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('favourite_id')
    )
    op.create_index(op.f('ix_favourites_favourite_id'), 'favourites', ['favourite_id'], unique=False)

    op.create_table('favourite_posts',
        sa.Column('favourite_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('post_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['favourite_id'], ['favourites.favourite_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('favourite_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourite_posts')
    op.drop_index(op.f('ix_favourites_favourite_id'), table_name='favourites')
    op.drop_table('favourites')
    # ### end Alembic commands ###
