"""update post material relationships

Revision ID: bc562631a595
Revises: bbcd4defc3f5
Create Date: 2025-06-10 16:33:49.366129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc562631a595'
down_revision: Union[str, None] = 'bbcd4defc3f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_material', sa.Column('unit', sa.String(length=50), nullable=False))
    op.add_column('post_material', sa.Column('quantity', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'post_material', 'unit', ['unit'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_material', type_='foreignkey')
    op.drop_column('post_material', 'quantity')
    op.drop_column('post_material', 'unit')
    # ### end Alembic commands ###
