"""add unit table

Revision ID: bde4847944fd
Revises: 1effb80a7834
Create Date: 2025-06-10 14:28:22.654026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde4847944fd'
down_revision: Union[str, None] = '1effb80a7834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('unit_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'unit', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='unique')
    op.drop_column('unit', 'unit_id')
    # ### end Alembic commands ###
