"""create group_members table

Revision ID: e120ba49472f
Revises: 07eff5c13dfb
Create Date: 2025-06-11 14:05:19.894751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e120ba49472f'
down_revision: Union[str, None] = '07eff5c13dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'topic_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('groups', 'group_leader',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('groups', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_groups_group_id'), 'groups', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_group_id'), table_name='groups')
    op.alter_column('groups', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('groups', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('groups', 'group_leader',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('groups', 'topic_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
